preload = /home/Raddarin/Pictures/wallpaper/ygdrasill.jpg
preload = /home/Raddarin/Pictures/wallpaper/Red_Blosom.jpg
wallpaper {
    monitor = 
    path = /home/Raddarin/Pictures/wallpapers/hello-world-pixel-3840x2160-15168.png
    fit_mode = cover
}
$mainMod = SUPER 

splash = false
